### ISSUE TITLE
Feature request: .ini option to link also the _Arcade/cores directory to the organized one

### ISSUE THREAD

**Issue by cavemanxzx** [theypsilon/_arcade-organizer#16]
This would fix "Links dont work when organized folder is outside of _Arcade" this was Issue #1 without User action.
Another possible Feature would be just link the _alternatives dir as is.

**Comment by MAME-GETTER** [comment]
I don't think this is possible. The links and MRAs must live in _Arcade.

If this is not correct, prove me wrong.

**Comment by cavemanxzx** [comment]
I have it working since weeks.
my ini:
MRADIR=/media/fat/_Arcade 
ORGDIR=/media/fat/_Arcade_Organized

after organizing i made a script with this:

ln -s /media/fat/_Arcade/cores/ -t /media/fat/_Arcade_Organized

everything runs fine with it.

For the alternatives Stuff i use

ln -s /media/fat/_Arcade/_alternatives/ -t /media/fat/_Arcade_Organized

for renaming
mv /media/fat/_Arcade_Organized/_alternatives "/media/fat/_Arcade_Organized/_6 Alternatives&BETA"

As it's not parsed i use it also for my jotego beta stuff and other mra that not be organized.

**Comment by MAME-GETTER** [comment]
Let me further research this.

**Comment by theypsilon** [comment]
Done
