### ISSUE TITLE
Separate and label Jotego Open Beta and Closed Beta cores?

### ISSUE THREAD

**Issue by CirclesCenter** [theypsilon/_arcade-organizer#40]
Hello, I'm wondering it if would be possible for your utility to handle separating and identifying Jotego cores that require a Patreon Key from the Open Public Betas. 

Currently you can only either opt in to Beta or out of it. So right now when you scroll your game list the Closed Beta (unplayable without a patreon subscription) games are right in with the rest of your games with no way of knowing they're not playable until you're in-game.

Is this something your tool could resolve?

**Comment by theypsilon** [comment]
From the preservation point of view, it doesn't seem necessary to add that kind of information to any of our metadata files, since it doesn't describe the game, nor the hardware, and is gonna become obsolete information in few months anyways so it would increase the maintenance overhead.
