### ISSUE TITLE
sorting is going wrong...

### ISSUE THREAD

**Issue by cavemanxzx** [theypsilon/_arcade-organizer#42]
...when -setname- is not set in MRA. It is not okay when it's there and empty like in Computer Space or Pacmanic Miner or MIssing like in all DoubleDragon II MRA.

Known Bad MRA:
all DoubleDragon II
Pacmanic Miner
Computer Space
Asteroids Deluxe (the one with Background from Releases Folder)

**Comment by cavemanxzx** [comment]
two more found Cosmic Alien and MagicalSpot

**Comment by theypsilon** [comment]
Is this issue still happening? I recently fixed an issue affecting Double Dragon 2, because of the ":" character. So it might be fixed now. Please, let me know if you still experience the problem.

**Comment by cavemanxzx** [comment]
It's working partially.

Pacmanic Miner, Asteroids Deluxe  and Computer Space sorting ok.

DD II and Cosmic Alien,MagicalSpot and Space Panic not.

Missing after Sorting from A-Z and the other Lists. Except sorted by Core then they are named Computer Space.

**Comment by sjbaines** [comment]
Selecting 'Computer Space' from e.g. Organised->A-E, actually fires up Asteroids Deluxe.
I'm not certain if this is the exact same issue - but it sounds closely related even if it isn't.

**Comment by cavemanxzx** [comment]
It should be. Look into collections/mister core/jtdd2 or cosmic there is also a Computer Space.

**Comment by theypsilon** [comment]
I made the Arcade Organize to ignore files with setname. That way there is no room for these kind of problems. Closing this, but feel free to reopen if you see anything wrong related to this issue.
