### ISSUE TITLE
Noticed some incorrect organization

### ISSUE THREAD

**Issue by prurigro** [theypsilon/_arcade-organizer#44]
I'm not sure I follow how the script is determining how to categorize things so it might not be an issue related to it, but on the chance that it is:

Under Collections -> By Manufacturer -> Cave there's Progear, which actually belongs to Capcom, and then DoDonPachi should be listed under Cave.

Either way, thanks for the awesome tool!

**Comment by amoore2600** [comment]
Progear is a 2001 horizontally scrolling bullet hell arcade video game developed by CAVE and published by Capcom for the CP System II board. Wikipedia
Initial release date: January 17, 2001
Developer: CAVE
Genre: Manic shooter
Mode: Cooperative video game
Arcade system: CP System II
Publishers: CAVE, Capcom
