### ISSUE TITLE
Duplicate entre for SF II Hyper fighting

### ISSUE THREAD

**Issue by PapiFed** [theypsilon/_arcade-organizer#45]
Game appears twice in the Cores list, they are differentiated by a double spacing in between two words in the title (don't have it at hand when raising this issue).
In summary it appears we have two identical .mra but with different spelling.

**Comment by PapiFed** [comment]
Closing this issue as I could confirm this issue no longer occures, very likely a once-off problem or wrong manipulation on my end.

**Comment by theypsilon** [comment]
I missed this one somehow. I think that probably came from the old updater. But thanks for the heads up!
