### ISSUE TITLE
No "_Organized" folder after running the script

### ISSUE THREAD

**Issue by Yamato-san** [theypsilon/_arcade-organizer#46]
Hi everyone,

I am encountering a strange problem with the great arcade-organizer script.
It worked before so I don't know what is happening there for sure.

I just ran the update-all script (with the "new downloader" enabled for the first time). Arcade-organizer was enabled as always.

Now there is no "_Organized" folder anymore in my "_Arcade" directory.

As I don't know what information might be helpful to find the issue I will provide what I can:

Within the .config/arcade-organizer directory I got a data.zip (125,9 kb) and a installed_names.txt (11,2 kb)

**My update_arcade_organizer.ini looks like this:**

REGION_DIR="false"
CORE_DIR="false"
YEAR_DIR="false"
CATEGORY_DIR="false"
SERIES_DIR="false"
BEST_OF_DIR="false"
RESOLUTION_DIR="false"
RESOLUTION_15KHZ="false"
RESOLUTION_24KHZ="false"
RESOLUTION_31KHZ="false"
ROTATION_DIR="false"
ROTATION_0="false"
ROTATION_90="false"
ROTATION_270="false"
ROTATION_180="false"
FLIP="false"
MOVE_INPUTS_DIR="false"
NUM_BUTTONS_DIR="false"
SPECIAL_CONTROLS_DIR="false"
NUM_CONTROLLERS_DIR="false"
COCKTAIL_DIR="false"
NUM_MONITORS_DIR="false"
HOMEBREW="2"
BOOTLEG="2"
ENHANCEMENTS="2"
TRANSLATIONS="2"
HACKS="2"

**My update-all logfile looks likes this:**

Downloading the most recent _arcade-organizer.sh script.

STARTING: _ARCADE-ORGANIZER
Reading INI (update_arcade-organizer.ini):
OK

Arcade Organizer 2.0
Arguments:
ARCADE_OFFSET_DIRECTORY=/media/fat/_Arcade/_Arcade Offset
AZ_DIR=true
BEST_OF_DIR=false
BOOTLEG=2
CATEGORY_DIR=false
CORE_DIR=false
DECADES_DIR=true
FLIP=false
HOMEBREW=2
MAD_DB=https://raw.githubusercontent.com/misteraddons/MiSTer_Arcade_MAD/db/mad_db.json.zip
MANUFACTURER_DIR=true
MOVE_INPUTS_DIR=false
MOVE_INPUTS_NOT_SUPPORTED=[]
MRADIR=/media/fat/_Arcade/
NUM_BUTTONS_DIR=false
NUM_BUTTONS_MAXIMUM=9999
NUM_MONITORS_DIR=false
ORGDIR=/media/fat/_Arcade/_Organized
PLATFORM_DIR=true
PLAYERS_DIR=true
PLAYERS_NOT_SUPPORTED=[]
PREPEND_YEAR=false
REGION_DIR=false
REGION_MAIN=DEV PREFERRED
REGION_OTHERS=1
RESOLUTION_15KHZ=false
RESOLUTION_24KHZ=false
RESOLUTION_31KHZ=false
RESOLUTION_DIR=false
ROTATION_0=false
ROTATION_180=false
ROTATION_270=false
ROTATION_90=false
ROTATION_DIR=false
SERIES_DIR=false
SKIPALTS=true
SPECIAL_CONTROLS_DIR=false
SPECIAL_CONTROLS_NOT_SUPPORTED=[]
TOPDIR=
VERBOSE=false
YEAR_DIR=false
YEAR_HIGH=9999
YEAR_LOW=0

Downloading Mister Arcade Descriptions database
MD5 Hash: b9fe00bab5b5b1032f80d9051d564a34

Different AO version detected.

Some ORGDIR directories are missing.

Last run file not found.

The installed names.txt is new.

The MAD database is new.

Performing a full build.

Organizing 453 MRAs.

MRA                                          Core       Year Manufactu. Category
################################################################################
Aurail (US, Set 3).mra                       jts16      1990 Sega       Shooter 
Black Dragon (JP).mra                        jtbtiger   1987 Capcom     Platform
Centipede (Rev 3).mra                        Centipede  1980 Atari      Shooter 
Crazy Kong (Orca Bootleg) [bl].mra           CrazyKong  1981 Falcon     Platform
Daimakaimura (Japan Resale Ver.) (JP, Resale jtcps1     1988 Capcom     Platform
DoDonPachi (20120212 Arrange Ver. 1.1).mra   Cave       1997 CAVE       Shooter 
DoDonPachi (20120212 Arrange Ver. 1.1).mra   Cave       1997 CAVE       Shooter 
DoDonPachi (20120212 Arrange Ver. 1.1).mra   Cave       1997 CAVE       Shooter 
Donkey Kong (Spanish, Crazy Kong) [bl].mra   CrazyKong  1981 Nintendo   Platform
Double Dragon (JP).mra                       jtdd       1987 Technos    Beat 'em
Galaga 3 (GP3 Rev D).mra                     Gaplus     1984 Namco      Shooter 
Grobda (W, New Ver.).mra                     Druaga     1984 Namco      Shooter 
Gyruss.mra                                   Gyruss     1983 Konami     Shooter 
Jackal (W) [bl].mra                          Jackal     1986 Konami     Shooter 
Jackal (W).mra                               Jackal     1986 Konami     Shooter 
Jackal (W, Rotary).mra                       Jackal     1986 Konami     Shooter 
Kick-Man.mra                                 MCR1       1980 Midway     Ball and
Mega Man- The Power Battle (CPS1.5 Qsound) [ jtcps1     1995 Capcom     Fighting
Opa Opa (Rev A, unprotected).mra             SMS        1987 Sega       Maze    
Opa Opa (MC-8123, 317-0042).mra              SMS        1987 Sega       Maze    
Pitfall II - The Lost Canvas (Japan) [315-50 SEGASYS1   1985 Sega       Platform
Pleiades (Centuri).mra                       Pleiads    1981 Centuri    Shooter 
Rush'n Attack (US).mra                       rshnatk    1985 Konami     Run 'n' 
Shinobi (W, S16B Set 5).mra                  jts16      1987 Sega       Platform
Solomon no Kagi (JP).mra                     SolomonsKe 1986 Tecmo      Platform
Space Invaders Part II (Taito, Bigger ROMs). SpaceInvad 1979 Taito      Shooter 
Star Jacker (Alt).mra                        SEGASYS1   1983 Sega       Shooter 
Star Jacker (Japan) [No Protection].mra      SEGASYS1   1983 Sega       Shooter 
Street Fighter II'- Hyper Fighting (W, 92120 jtcps1     1992 Capcom     Fighting
Street Fighter Zero 2 (AS, 960826).mra       jtcps2     1996 Capcom     Fighting
Tetris (Cocktail, Set 1).mra                 AtariTetri 1989 Atari      Puzzle  
Tokio (Scramble Formation) [bl].mra          jtbubl     1986 Taito      Shooter 
Tokushu Butai Jackal (JP).mra                Jackal     1986 Konami     Shooter 
Top Gunner (US) [bl].mra                     Jackal     1986 Konami     Shooter 
Top Gunner (US).mra                          Jackal     1986 Konami     Shooter 
Transformer.mra                              SMS        1986 Sega       Shooter 
Up'n Down (Japan) [315-5030].mra             SEGASYS1   1983 Sega       Racing  
Vampire Savior 2- The Lord of Vampire (JP, 9 jtcps2     1997 Capcom     Fighting
Darkstalkers- Jedah's Damnation (EU, 970519, jtcps2     1997 Capcom     Fighting
################################################################################
2.0 ver. by theypsilon
FINISHED: _ARCADE-ORGANIZER

**Please note that I have all official arcade cores installed including everything from Jotego.**

If some other information is needed to solve the issue please let me know.

Thank you very much!

**Comment by theypsilon** [comment]
Hi @Yamato-san , a couple of questions.
Are you using any USB drive or CIFS in your setup?
Did you check by entering in the system that the _Organized folder doesn't show up at all under /media/fat/_Arcade ?

A possible solution would be going to Update All Settings Screen > Arcade Organizer > Advanced Submenu hitting the Clean Folders option and running the script once again.

**Comment by Yamato-san** [comment]
Hi theypsilon,
thanks for your reply!

> Are you using any USB drive or CIFS in your setup?

No, everything is stored on the internal Micro SD card.

> Did you check by entering in the system that the _Organized folder doesn't show up at all under /media/fat/_Arcade ?

Yes, I have checked. The folder is not there. I tried creating it and running the script again, but then the folder is deleted because it is empty.

> A possible solution would be going to Update All Settings Screen > Arcade Organizer > Advanced Submenu hitting the Clean Folders option and running the script once again.

When I toggle that option under advanced settings it tells me that „Organized folder doesn‘t exist“. Running the script again afterwards makes no difference unfortunately.

Any more suggestions?
Thank you for your help.

**Comment by MAME-GETTER** [comment]
Is the SDcard full?

**Comment by Yamato-san** [comment]
> Is the SDcard full?

No, still 302 GB of available space.

**Comment by theypsilon** [comment]
I would try manually create the folder _Arcade/_Organized and see if there is any issue in your filesystem stopping you from doing that.

Also, after running it again, please share your new Scripts/.config/update_all/update_all.log

**Comment by Yamato-san** [comment]
Is there anything else I could try?
What about the update_all.log file. Does it contain any clue what is going wrong here?
Thanks for your help!

**Comment by theypsilon** [comment]
Hello, are you still having the same problem?

**Comment by Yamato-san** [comment]
Unfortunately yes.

I‘ve tried again after the rescent update to version 1.5 Downloader script and official PSX core release. It‘s still the same. Maybe deleting specific config files will help?

**Comment by theypsilon** [comment]
I've found the issue. You've selected false for resolutions 15khz, 24khz and 31khz. This means, you opt-out of all games. Try put them to true and you'll see games getting installed. Let me know if this helps!

**Comment by Yamato-san** [comment]
YES - that‘s it. Thank you so much!

I didn’t realize these toggles were meant for opting-out games entirely that match these resolutions. Makes total sense now. Thanks for clarifying this!
