### ISSUE TITLE
Shinobi not appearing in _organized folder - MRA checked

### ISSUE THREAD

**Issue by geekmiki** [theypsilon/_arcade-organizer#47]
Hi,

Shinobi is not appearing in the _Organized folder neither by letter, platform, core, genre, etc.
I have checked the MRA with the mra_rom_check.sh script and it's fine.
I am aware that the arcade organizer is based on the metadata of the MRAs, but in this case if I compare the Shinobi MRA to other System16 MRAs that are organized, they have the exact same metadata fields.

If the problem lies in the MRA, what is missing/should be changed so that it's picked up by the organizer script?

Thank you i advance!

**Comment by theypsilon** [comment]
Arcade Organizer is using the metadata contained here: https://github.com/misteraddons/MiSTer_Arcade_MAD
Therefore it needs to get updated there first.

**Comment by Toryalai1** [comment]
This is working with the Toya Database. Can be closed
