### ISSUE TITLE
Missing Titles in CAVE Manufacturer Directory

### ISSUE THREAD

**Issue by citizen-why** [theypsilon/_arcade-organizer#49]
Hi there,

I've been keeping the arcade organizer fairly up-to-date, but after running it this evening I noticed Dodonpachi is not showing up in the Organized Folder under CAVE - the only titles showing up are Progear and the near release ESP Ra De. I can see the Dodonpachi title in the base directory (not organized) - but it is entirely missing from the CAVE manufacturer directory. I wasn't sure if its an oversight, I'm doing something wrong, or I'm just incorrect in my understanding.

**Comment by advert665** [comment]
I came here to report exactly this. Dodonpachi also doesn’t show up in the platform section under Cave 68000 either, despite being on that platform.

**Comment by theypsilon** [comment]
Arcade Organizer is using the metadata from this repository: https://github.com/misteraddons/MiSTer_Arcade_MAD

Please report it there.

**Comment by Toryalai1** [comment]
This is now fixed with the new Toya Database. Can be closed
