### ISSUE TITLE
Some MRAs don't get organized

### ISSUE THREAD

**Issue by aghus** [theypsilon/_arcade-organizer#50]
I have my setup where the Alternatives and HBmame are not enabled, also I have selected the database that points to `theypsilon/MAD_Database_MiSTer/blob/db/mad_db.json` and I have noticed that some MRAs do not get organized in any of the organized folders.

One of them is Black Tiger. After running the `Update_All`, Black Tiger is nowhere to be seen but I can see a Black Dragon on `_Organized\_5 Extra Software\_1 Bootleg\`.

I can see on `https://github.com/theypsilon/MAD_Database_MiSTer/blob/main/mad/Black%20Tiger.mad` clearly says  it is not an alternative rom, but when I look at the `https://github.com/theypsilon/MAD_Database_MiSTer/blob/db/mad_db.json.zip` it shows this:
```
"blktiger": {
        "alternative": true,
        "bootleg": true,
        "category": [
            "Fighter / Warriors"
        ],
        "file": "Black Dragon (bootleg).mra",
        "manufacturer": [
            "Capcom"
        ],
        "name": "Black Dragon (bootleg)",
        "rotation": 0,
        "year": 1987
},
```

I'm wondering if there is a mistake in how it parses the MAD files to create the database and makes a bad assumption and this is the result? 

Also it's possible that there are more games that act like this. 

Another game that I noticed that does not get organized is Wonder Boy III. 
In this case the non-alternative mra uses rom `wb33` meanwhile the MAD file from`https://github.com/theypsilon/MAD_Database_MiSTer/blob/main/mad/` it points to rom is `wb3`. 
That would be correct for mame because `wb3` apparently is the parent rom, but I don't know why Jotego would choose `wb33` as the non-alternative ROM.

Again, it is possible that more mras that don't get organized by this reason.

Thanks for your time and the work you do on the Mister community.

**Comment by theypsilon** [comment]
Hi, thanks for opening your issue. I'm reactivating the job that was generating that file since was stopped months ago. People are using now the repository from MisterAddons which is the one enabled by default, since mine was never intended to cover all the metadata (I would never have free enough time for that).

After the cronjobs run, let's take a look again.

**Comment by aghus** [comment]
Yes, i have noticed that by default was enabled the repository from misteraddons, but even if it has more metadata in the MAD files, it seems that is older than yours.

Now I have seen that new MAD files have been added to the repo, but if I run the organizer does not change a thing.

I looked up the output log of `Generate_DBs.py` and I have noticed this
```
mad/_alternatives/_Black Tiger/Black Dragon (bootleg).mad
mad/_alternatives/_Black Tiger/Black Dragon (Japan).mad
REPEATED! mad/_alternatives/_Black Tiger/Black Dragon (Japan).mad
mad/Black Hole.mad
mad/_alternatives/_Black Tiger/Black Tiger (bootleg set 1).mad
REPEATED! mad/_alternatives/_Black Tiger/Black Tiger (bootleg set 1).mad
mad/_alternatives/_Black Tiger/Black Tiger (bootleg set 2).mad
REPEATED! mad/_alternatives/_Black Tiger/Black Tiger (bootleg set 2).mad
mad/_alternatives/_Black Tiger/_NotWorking/Black Tiger (Modular System).mad
REPEATED! mad/_alternatives/_Black Tiger/_NotWorking/Black Tiger (Modular System).mad
mad/_alternatives/_Black Tiger/Black Tiger (older).mad
REPEATED! mad/_alternatives/_Black Tiger/Black Tiger (older).mad
mad/_alternatives/_Black Tiger/Black Tiger - Black Dragon (mixed bootleg).mad
REPEATED! mad/_alternatives/_Black Tiger/Black Tiger - Black Dragon (mixed bootleg).mad
mad/Black Tiger.mad
REPEATED! mad/Black Tiger.mad
```
All the Black Tiger MRAs are all using the same setname (`blktiger`), and in the `Generate_DBs.py` in line 219 it checks if the setname is repeated, so all the next ones are being ignored. I don't know if that would be the only condition needed??

**Comment by aghus** [comment]
Thanks for your fast response. I understand the reasons, I wondered if this was really a bug or not given that a repeated.txt file is also generated, and now is more clear to me.

Given that now I know why it works that way, the issue can be closed.
