### ISSUE TITLE
Feature Request: Support Favorites

### ISSUE THREAD

**Issue by dpan** [theypsilon/_arcade-organizer#54]
Not sure if this is the right place for this request, but it would be great to be able to tag games as favorites and have them appear in the structure under a favorites folder

**Comment by Toryalai1** [comment]
There is a script that does this already: https://github.com/wizzomafizzo/MiSTer_Favorites

**Comment by theypsilon** [comment]
Indeed, wizzo script is pretty good for that purpose. But thanks for the suggestion!
