### ISSUE TITLE
Street Fighter II' - Hyper Fighting - World 921209 missing from Organised Lists

### ISSUE THREAD

**Issue by keungk** [theypsilon/_arcade-organizer#55]
Not in Collections and probably others.

**Comment by Toryalai1** [comment]
What MAD database are you using? In my database, it is available now

**Comment by keungk** [comment]
ok that works, but there isnt a street fighter collection

**Comment by Toryalai1** [comment]
There sure is. If you go to 3 Collections/6 By Series/Street Fighter. There you have a folder with available street fighter games

**Comment by keungk** [comment]
![image](https://user-images.githubusercontent.com/2817123/188939181-13c8657b-2a91-454f-a4b7-0d612c4a68a2.png)

**Comment by Toryalai1** [comment]
You are not using the database to which I am referring. Switch it to the Toya Database

**Comment by theypsilon** [comment]
Should be fixed in Toya database, take a look there please!
