### ISSUE TITLE
Horizontal filter

### ISSUE THREAD

**Issue by mrchrisster** [theypsilon/_arcade-organizer#59]
Not sure if this is the right place to report, but I noticed `/media/fat/_Arcade/_Organized/_4 Video & Inputs/_2 Rotation/_Horizontal/Air Duel (Japan, M72 hardware).mra` is not a horizontal game

**Comment by theypsilon** [comment]
@mrchrisster are you using the default MAD DB? If you haven't changed that option in update_all, that's the one you are likely using. In that case we should ping @toryalai1, he host the DB in this repository: https://github.com/Toryalai1/MiSTer_ArcadeDatabase

**Comment by mrchrisster** [comment]
copy that thanks!
